### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by johndh** [Andrettin/Wyrmgus#104]
[log_of_stratagus_0.txt](https://github.com/Andrettin/Wyrmgus/files/466051/log_of_stratagus_0.txt)

Just exploring around and shooting Teutons.

**Comment by Andrettin** [comment]
Oh =/ Did you get any output for the crash? And does stderr.txt say anything?

**Comment by johndh** [comment]
game ends
Segmentation fault

That's it.

**Comment by johndh** [comment]
I can reproduce this crash sometimes by loading a particular save file from inside a particular mission.  If I load from the main menu, there is no crash.  I don't remember doing this during the initial crash, but I might have.

If I load a different game then try to load autosave.sav.gz from within the mission, it loads correctly.
If I load autosave.sav.gz then try to load any sav file from within the mission, I sometimes get a seg fault.
[autosave.sav.gz](https://github.com/Andrettin/Wyrmgus/files/466073/autosave.sav.gz)
[game.sav.gz](https://github.com/Andrettin/Wyrmgus/files/466074/game.sav.gz)

If I start the mission from the beginning and load autosave.sav.gz, it loads correctly.

**Comment by Andrettin** [comment]
Thank you! That was very helpful, I was able to reproduce the crash as well. It has been fixed now:
https://github.com/Andrettin/Wyrmsun/commit/82108723ecb1c077a27b0e5c4f8c18e7bd7c1627
