### ISSUE TITLE
Crash when a new chieftain rises to power

### ISSUE THREAD

**Issue by johndh** [Andrettin/Wyrmgus#105]
`[string "if (GenericDialog ~= nil) then GenericDialog("Chieftain Desider..."]:1: unfinished string near '<eof>'`

This happened right when a battle in GSM ended, during which my chief died, so it seems to be that Desiderius x6 caused a crash.

**Comment by Andrettin** [comment]
No longer applicable as the bug had been fixed, and now the GSM isn't even in the game anymore.
