### ISSUE TITLE
Fix Appveyor compilation

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#106]
Currently it seems like cmake lacks oaml library. It's not clear from the logs, but you can try to do the following things:
1. Change `url = https://github.com/marcelofg55/oaml` from .gitmodules to `https://github.com/oamldev/oaml` as it's the correct link now. However the first ono redirects to the correct one.
2. Try to add something like this (found it [here](https://github.com/vtex/appveyor-scripts))

```
install:
  - cmd: git submodule -q update --init
```

**Comment by Andrettin** [comment]
Thank you! I tried it, but unfortunately it isn't recognizing the submodule for some reason.

**Comment by KroArtem** [comment]
Yes, seems like it doesn't work. I'm not the expert in appveyor either so it's hard to say what's missing. Anyway, this red cross icon disturbes for several weeks now. :)

**Comment by KroArtem** [comment]
I want to raise this ticket again. As we know from Appveyor logs, oaml dependencies are not loaded.
`shallow_clone: true` means that (citing their documentation):

> As the title says, this option is specific to GitHub and Bitbucket only. It uses their respective REST API to download specific commit of the repository as zip archive and then unpacks it on build worker machine. This feature works for regular commits, branch commits and pull requests.

However, still there is a `before_build` step that allows to download some files, unzip them and so on and so forth. I think there is a possibility to enter loaded sources (it seems like your downloaded sources are a root folder so there is no need to cd anywhere) and do
```git submodule update --init --recursive```
as it's been suggested [here](http://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules)

I suggest trying this and see what happens.

**Comment by Andrettin** [comment]
It is downloading the OAML now and apparently that is working correctly, but it still doesn't build =/

**Comment by KroArtem** [comment]
re our previous attempts: it seems like shallow_clone option was downloading zip archive without git information (thus it wasn't a git repo). When you've made changes to download oaml as an archive, it wasn't placed correctly (it was extracted to /build directory instead of /src/oaml)

I've made it to load oaml and start compilation but seems like oaml requires to be built before building Wyrmgus. You can check it in forked repo. Will try to fix it tomorrow.

**Comment by KroArtem** [comment]
I just missed that oaml installation also started in my latest build but it didn't manage to find oggvorbis lib. However, this library is in dependencies/lib so there are several ideas how to solve it. I'm definitely not a pro in VS and Windows, anyway, it would be easier to fix this problem directly in Windows. It won't happen very soon, though.

**Comment by akien-mga** [comment]
Current appveyor builds still seem not to pull the submodule properly. This is supposed to be supported, I use it for Godot: https://github.com/GodotBuilder/godot-builds/blob/master/appveyor.yml#L82

Your current appveyor script downloads the 1.2 release tarball for oaml, but it just extracts it in the root without putting its contents in `src/oaml/`, so it can't work.

**Comment by Andrettin** [comment]
Unfortunately when I try to pull the submodule, I get the following error:

```
Running Install scripts
git submodule update --init --recursive
fatal: Not a git repository (or any of the parent directories): .git
```

I suppose I'm missing some sort of preparation which has to be done regarding paths?

**Comment by akien-mga** [comment]
Well, you don't seem to have any build instructions (`build_script:`) :)

**Comment by Andrettin** [comment]
Apparently the issue was the lack of a "project:" field under a "build:" one. After doing that, it got past that point :) Hopefully it will build now.

**Comment by Andrettin** [comment]
Hmm, it got stuck on some OAML unresolved externals at the end =/

**Comment by akien-mga** [comment]
Check further up the log, you lack OAML dependencies so it doesn't build:
```
PrepareForBuild:
  Creating directory "Win32\Release\oaml\".
  Creating directory "Win32\Release\oaml\oaml.tlog\".
InitializeBuildStatus:
  Creating "Win32\Release\oaml\oaml.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ComputeCustomBuildOutput:
  Creating directory "C:\projects\wyrmgus\build\CMakeFiles\oaml.dir\src\oaml-stamp\Release\".
  Creating directory "C:\projects\wyrmgus\build\CMakeFiles\Release\".
CustomBuild:
  Building Custom Rule C:/projects/wyrmgus/CMakeLists.txt
  CMake does not need to re-run because C:\projects\wyrmgus\build\CMakeFiles\generate.stamp is up-to-date.
  Creating directories for 'oaml'
  No download step for 'oaml'
  No update step for 'oaml'
  No patch step for 'oaml'
  Performing configure step for 'oaml'
  -- The C compiler identification is MSVC 19.0.24215.1
  -- The CXX compiler identification is MSVC 19.0.24215.1
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  Debug mode: No (Enable by param -DCMAKE_BUILD_TYPE=Debug)
  Build static: Yes (Disable by param -DENABLE_STATIC=OFF)
  Build shared: No  (Enable by param -DENABLE_SHARED=ON)
  Build AudioPluginOAML: No  (Enable by param -DENABLE_UNITYPLUGIN=ON)
  Build OGG support: Yes (Disable by param -DENABLE_OGG=OFF)
  Build RtAudio support: Yes (Disable by param -DENABLE_RTAUDIO=OFF)
  CMake Error at cmake/modules/FindOggVorbis.cmake:58 (message):
    Could NOT find OggVorbis libraries
  Call Stack (most recent call first):
    CMakeLists.txt:86 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "C:/projects/wyrmgus/src/oaml/CMakeFiles/CMakeOutput.log"
```

**Comment by akien-mga** [comment]
BTW it would have been cleaner to do trial and error in a feature branch instead of master ;) but it's not big deal.

**Comment by Andrettin** [comment]
@akien-mga Thanks, I missed that. Strange that it isn't finding Ogg/Vorbis, since those are included in Stratagus' dependencies.

**Comment by akien-mga** [comment]
You might need to find a way to pass `-DCMAKE_PREFIX_PATH="%cd%\\dependencies"` to the oaml CMake script when you chain it.

**Comment by Andrettin** [comment]
Thanks again for the help, Akien :) About it being cleaner doing trial and error with the appveyor on a separate branch - I suppose you're right, I'll keep that in mind.

**Comment by KroArtem** [comment]
Closing this issue as of https://github.com/Andrettin/Wyrmsun/issues/21#issuecomment-504457419
