### ISSUE TITLE
wyrmgus does not uses the oaml's cmake file

### ISSUE THREAD

**Issue by bmorel** [Andrettin/Wyrmgus#118]
The last oaml's commit is to give systems to allow people to use it more easily.
Obviously, wyrmgus does not uses that system (since oaml integration in it is older than that commit).

This is related to issues #115 ,#103 and #99

**Comment by Andrettin** [comment]
Hey, do you including oaml.cmake.in in the /cmake/modules/ folder (besides updating the repo to use the latest OAML commit, of course), or something else?

**Comment by bmorel** [comment]
I don't understand the question?

**Comment by Andrettin** [comment]
What do you recommend doing? Just updating to use the latest OAML version, or something else as well?

**Comment by bmorel** [comment]
I think the ideal way would be to use upstream's cmake module instead of wyrm's one, but let's face the reality: there is actual code that works (at least, I guess it does for some people, since I didn't had luck with it) and it would be a shame to throw it as long as it is not sure that using upstream's way works fine.

The best way I can think about is to check for upstream detection, and if not found, fallback on current system.

**Comment by Andrettin** [comment]
Closed as the game no longer uses OAML as a dependency.
