### ISSUE TITLE
MORPHOS support

### ISSUE THREAD

**Issue by BeWorld2018** [Andrettin/Wyrmgus#131]
It's possible to submit change to your code for support MORPHOS platform ?

**Comment by Andrettin** [comment]
Hey, you mean making a pull request with platform-specific code to support MORPHOS? Sure, that's absolutely fine :)

**Comment by BeWorld2018** [comment]
hi, ok i push my diff with #ifdef __MORPHOS__

**Comment by BeWorld2018** [comment]
I modify directy code with github site (edit), do you see my modification ?
