### ISSUE TITLE
sigsegv when loading just saved game

### ISSUE THREAD

**Issue by AMDmi3** [Andrettin/Wyrmgus#150]
Steps to reproduce (Wyrm{sun,gus} 3.5.1):
- start a _Caverns of flame_ quest
- click through introduction dialogs
- save the game
- load just saved game

Save game and backtrace attached.
[game.sav.gz](https://github.com/Andrettin/Wyrmgus/files/2729786/game.sav.gz)
[gdb.txt](https://github.com/Andrettin/Wyrmgus/files/2729787/gdb.txt)

**Comment by AMDmi3** [comment]
For instance, this only happens with some quests. For example, with _The wyrm_ as well but not _The mead of wisdom_ or _The battle of magetobria_

**Comment by Andrettin** [comment]
Thank you for reporting the bug :) I've successfully reproduced and fixed it here:
https://github.com/Andrettin/Wyrmsun/commit/30aedf7d76165b5d5cba4dec63dca38a581bb128

**Comment by AMDmi3** [comment]
:+1: :+1: :+1:
