### ISSUE TITLE
4.0.1 link failure

### ISSUE THREAD

**Issue by AMDmi3** [Andrettin/Wyrmgus#155]
`wyrmgus::point::distance_to(QPoint const&, QPoint const&)` is declared as `constexpr extern`. I don't think this makes any sense and it causes link failure:

```
ld: error: undefined symbol: wyrmgus::point::distance_to(QPoint const&, QPoint const&)
>>> referenced by mainscr.cpp
>>>               CMakeFiles/stratagus.dir/src/ui/mainscr.cpp.o:(void std::__1::__sort<InfoPanel_draw_no_selection()::$_0&, CPlayer const**>(CPlayer const**, CPlayer const**, InfoPanel_draw_no_selection()::$_0&))
```

Full log https://people.freebsd.org/~amdmi3/wyrmgus.log

**Comment by Andrettin** [comment]
You are absolutely right... thanks for the heads up!

I've made a fix here:
https://github.com/Andrettin/Wyrmgus/commit/a6ef0373a73f2c9b1be886e1381f153f1f1c9d8c

**Comment by AMDmi3** [comment]
Fix confirmed
