### ISSUE TITLE
4.1.3 installs static library instead of a binary

### ISSUE THREAD

**Issue by AMDmi3** [Andrettin/Wyrmgus#168]
4.1.3 suddenly installs bin/libstratagus.a instead of bin/wyrmgus. Is this expected?

**Comment by Andrettin** [comment]
No, it was an oversight, sorry :(

I made Stratagus into a static library so that I could link it against a unit test executable, and this caused an issue with the installation. @akien-mga has fixed it:
https://github.com/Andrettin/Wyrmgus/pull/166

**Comment by AMDmi3** [comment]
The fix works for me, thanks!
