### ISSUE TITLE
Clarification on how Factions can be set to upgrade to/from one another

### ISSUE THREAD

**Issue by joaocaju** [Andrettin/Wyrmgus#193]
If I recall correctly, before the update that added Tribal bonuses and government systems, each faction (ex.: Joruvellir, Knalga, Shorbear) could be individually coded to descend or ascend to one another.

It seems that is no longer the case, but I can't find how the current "faction tree" would look like and how to allow custom factions to be researched from the default ones.

Looking at the dwarven civs in the 'Data' folder, all I could see is some factions seemingly have no code about that (like the Brisings), while others only have something like this:
```
joruvellir = {
	parent_faction = goldhoof_clan
	type = polity [...]
	default_tier = duchy
	max_tier = empire [...]
	conditions = {
		scripted_condition = is_civilized_or_has_prerequisites [...] }
```

**Comment by Andrettin** [comment]
This is actually being changed for the next version back to predefined faction lists.

For example:
```
brising_clan = {
	name = "Brising Clan"
	adjective = "Brising"
	civilization = dwarven
	type = tribe
	color = red
	default_tier = county #clan
	icon = icon_flag_silver_hammer_on_red
	upgrade = upgrade_faction_brising_clan
	description = "The Brising clan was one of the first dwarven clans ever known. It made its home in Svarinshaug, where they tamed the fierce forces of nature."
	background = "In Norse mythology, \"Brising\" was an appelation used for the dwarves in general, or more specifically for the ones who created the necklace Brisingamen. \"Brising\" means \"flame\" in Old Norse."
	develops_to = {
		knalga
		lyr
	}
	core_settlements = {
		svarinshaug
	}
}
```

**Comment by joaocaju** [comment]
Noted! Just for curiosity, why is it changing back?

**Comment by Andrettin** [comment]
I felt that the dynamic way of selecting factions ended up making the process too generic (along with making the faction development menu too long), and the explicit list helps to better represent particular historical development paths.
