### ISSUE TITLE
Tweak/remove stratagus optional depends

### ISSUE THREAD

**Issue by AMDmi3** [Andrettin/Wyrmgus#2]
Stratagus, being a flexible engine, has a set of build tunables for enabling optional dependencies such as mikmod, mng, theora etc. Wyrmgus, otoh, being a specialized engine doesn't need suck flexibility as a set of formats needed for wyrmsun is known. To simplify packaging, it's be nice to either switch options corresponding to unneeded components to off or remove them along with specific dependency handling completely.

**Comment by Andrettin** [comment]
I see what you mean, but the idea is to keep Wyrmgus as flexible as Stratagus, and to make changes only where necessary to add features to Wyrmsun, to make it easier to port Wyrmgus code back to mainline Stratagus.

**Comment by AMDmi3** [comment]
Ok, then what optional depends are needed for wyrmsun? I've disabled practically everything and the game works fine. However my guess is that at least vorbis should be enabled for music support.

**Comment by Andrettin** [comment]
Pretty much only Vorbis should be necessary for Wyrmsun IIRC.

You are right that tweaking default option values would not create significant divergence with Stratagus, but I prefer to compile Wyrmgus with those settings on, as they can be useful to modders.

**Comment by AMDmi3** [comment]
Point taken, thank you.
