### ISSUE TITLE
Compiling with CMake < 3.1

### ISSUE THREAD

**Issue by akien-mga** [Andrettin/Wyrmgus#23]
I see that the requirements for the CMake version were upped to version 3.1 in this commit: e563860. I suppose this means that ```${CMAKE_CXX11_STANDARD_COMPILE_OPTION}``` is a new feature in CMake 3.1?

However, it makes it quite harder to build Wyrmgus against CMake 3.0, which is the version provided by most current Linux distributions (Debian Jessie, Mageia 5, ...).

If you want to support older CMake versions, you could probably add a fallback instruction to force the C++11 flags, see e.g. how we do it in OpenDungeons (probably not the simplest implementation, but it works):
https://github.com/OpenDungeons/OpenDungeons/blob/development/CMakeLists.txt#L120-L129

If you're fine with keeping a strict requires on CMake >= 3.1, feel free to close this issue as invalid :)

**Comment by Andrettin** [comment]
That sounds like a good idea. I wrote the following, based on your code:

```
set(WS_CXX11_FLAGS CACHE STRING "Compilation flags to enable C++11 support")

if(MSVC)
    # C++11 compilation flag is activated by default
    # Optimisation flags can be added if deemed useful
else()
    include(CheckCXXCompilerFlag)
    if(NOT OD_CXX11_FLAGS)
        CHECK_CXX_COMPILER_FLAG("-std=c++11" WS_CXX11_FLAG_SUPPORTED)
        # MinGW supports CXX11 flag but do not compile with it. However, it works with gnu++11
        if(WS_CXX11_FLAG_SUPPORTED AND NOT MINGW)
            set(WS_CXX11_FLAGS "-std=c++11" CACHE STRING "Compilation flags to enable C++11 support" FORCE)
        else()
            set(WS_CXX11_FLAGS "-std=gnu++11" CACHE STRING "Compilation flags to enable C++11 support" FORCE)
        endif()
    endif()
endif()

[...]

set(CMAKE_CXX_FLAGS "${WS_CXX11_FLAGS}${CMAKE_CXX_FLAGS}${CMAKE_CXX11_STANDARD_COMPILE_OPTION} ")
```

Does that look correct?

**Comment by akien-mga** [comment]
That looks good, apart from the last line: ```set(CMAKE_CXX_FLAGS "${WS_CXX11_FLAGS}${CMAKE_CXX_FLAGS}${CMAKE_CXX11_STANDARD_COMPILE_OPTION} ")```
Spaces between each variable are important to make sure you don't get something like ```-std=c++11-std=c++11```.

So you'd need:
```set(CMAKE_CXX_FLAGS "${WS_CXX11_FLAGS} ${CMAKE_CXX_FLAGS} ${CMAKE_CXX11_STANDARD_COMPILE_OPTION}")```
You might end up having the C++11 compile option defined several times if people use CMake >= 3.1, but that should not be an issue.

**Comment by Andrettin** [comment]
Thanks :) Change implemented in https://github.com/Andrettin/Wyrmgus/commit/f194f1c8700a293503a6e54d7002c832f0a5cebe

**Comment by akien-mga** [comment]
Thanks a lot :)
