### ISSUE TITLE
Linux game start issue

### ISSUE THREAD

**Issue by Andrettin** [Andrettin/Wyrmgus#31]
A player reported the following issue when running the Linux version, which caused the game to not start:

Program received signal SIGSEGV, Segmentation fault.
std::string::compare (this=<optimized out>, __s=0x52dd158 "orc") at /build/gcc-multilib/src/gcc-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:1397
1397    /build/gcc-multilib/src/gcc-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc: No such file or directory.
(gdb) bt
#0  std::string::compare (this=<optimized out>, __s=0x52dd158 "orc") at /build/gcc-multilib/src/gcc-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:1397
#1  0x000000000064c6e8 in PlayerRace::GetRaceIndexByName(char const*) const ()
#2  0x00000000006eba11 in CclDefineUnitType(lua_State*) ()
#3  0x00000000007aa66c in luaD_precall ()
#4  0x00000000007b3c58 in luaV_execute ()
#5  0x00000000007aaa7d in luaD_call ()
#6  0x00000000007a9d07 in luaD_rawrunprotected ()
#7  0x00000000007aac12 in luaD_pcall ()
#8  0x00000000007a82cf in lua_pcall ()
#9  0x0000000000654710 in LuaCall(int, int, bool) ()
#10 0x0000000000654a20 in LuaLoadFile(std::string const&) ()
#11 0x0000000000654cd3 in CclLoad(lua_State*) ()
#12 0x00000000007aa66c in luaD_precall ()
#13 0x00000000007b3c58 in luaV_execute ()
#14 0x00000000007aaa7d in luaD_call ()
#15 0x00000000007a9d07 in luaD_rawrunprotected ()
#16 0x00000000007aac12 in luaD_pcall ()
#17 0x00000000007a82cf in lua_pcall ()
#18 0x0000000000654710 in LuaCall(int, int, bool) ()
#19 0x0000000000654a20 in LuaLoadFile(std::string const&) ()
#20 0x000000000065f518 in LoadCcl(std::string const&) ()
#21 0x0000000000674f6e in stratagusMain(int, char**) ()
#22 0x000000000064aa9c in main ()
(gdb)

**Comment by akien-mga** [comment]
Could this user give more information about their distro and GCC version, and whether the issue was when running the game using the Steam runtime or directly with ```./wyrmsun64```?

Side note: You should probably put the stack trace between ``` markers to get it formatted as code, it will prevent having the hash numbers from making references to all your issues until issue 22 ;-) (it's too late for this time, but it's good to know for the next one).

**Comment by akien-mga** [comment]
Actually I am also getting a segmentation fault with the current binaries, I'll see if I can bisect the regression.

**Comment by akien-mga** [comment]
I just built the most recent commits (dc18b9e7 and wyrmsun's 0bdc181) and it seems to work fine. I see that you fixed an error in CclDefineUnitType, might it be related?

**Comment by akien-mga** [comment]
Looks like for once I was too confident and should have tested my binaries for 1.2.9 before getting them published :)

**Comment by Andrettin** [comment]
Akien, yes, that fix was related. When he mentioned that I noticed that the game could be getting "-1" as the civilization of orc units (since they have their civilization defined as orc for the encyclopedia, but the orc civilization doesn't really exist in the game, so when searched for for the new civilization-class-unit-type code the civilization's ID isn't found). I then made sure that the civilization-class-unit-type code would only be applied for a unit type if the civilization actually returned something different than "-1" (previously it only checked to see whether the civilization string was empty - assuming that a non-empty civilization string would refer to a real civilization).

But I thought that this wouldn't have solved the issue, as it seemed to have happened in the compare function rather than on that part of the code. Thanks for helping me debug this!

**Comment by akien-mga** [comment]
For the reference: fixed by dc18b9e.

**Comment by akien-mga** [comment]
Is the current wyrmsun repo ready for a 1.2.10 or 1.3.0 release, so that we can upload a fixed Linux build? I'll test building binaries of the current branch in my Ubuntu VM, the test I mentioned above was done directly on Mageia.

**Comment by akien-mga** [comment]
I tested 64-bit binaries of the master branch made with the Steam runtime locally, and they work fine against the current wyrmsun branch (i.e. they will work fine on Steam if released as the next stable build).
