### ISSUE TITLE
Linux Mikmod Issue

### ISSUE THREAD

**Issue by Andrettin** [Andrettin/Wyrmgus#32]
The following issue was reporting on the Steam forums when running the game on Linux:

./wyrmsun64: error while loading shared libraries: libmikmod.so.2: cannot open shared object file: No such file or directory

**Comment by akien-mga** [comment]
You can close this one as invalid, we already discussed about it. The binary is link against the Steam runtime (bundled Ubuntu 12.04 LTS libraries that are installed in the user's home directory), so the game must be run from Steam or using the run.sh script.

It's all explained in the linux_readme.txt, I'm not sure what more we can do :)

**Comment by Andrettin** [comment]
Ah yes, you're right! Thanks, I somehow forgot :)
