### ISSUE TITLE
Add support for stretch mode in fullscreen

### ISSUE THREAD

**Issue by akien-mga** [Andrettin/Wyrmgus#34]
Currently playing Wyrmsun on a 1920x1080 monitor, if tend to find the GUI and game mode quite small, especially reading text can quickly be bothersome.

I'd like to be able to play fullscreen with a lower resolution than my monitor's, with the game stretched (maybe preserving aspect ratio), so that everything appears bigger. For example I could play in 1600x900, it would be much more comfortable.

**Comment by akien-mga** [comment]
Not really related but worth noting: it looks like stratagus upstream is working towards a SDL2 port, removing OpenGL at the same time: https://code.launchpad.net/~stratagus/stratagus/sdl2

**Comment by Andrettin** [comment]
It should be possible to use fullscreen for resolutions lower than that of your monitor (I can for instance use 800x600 on fullscreen here, although my monitor's native resolution 1366x768). Some aspect ratios may not work, but being able to use a lower resolution with the same aspect ratio than your native one should definitely not be a problem; if it is not working then it sounds like a bug.

Did you try turning off fullscreen, putting the resolution at 1600x900, and then turning fullscreen on again?

For Linux, toggling the full screen is done by this simple line in ToggleFullScreen() (line 1212 of \src\video\sdl.cpp):
SDL_WM_ToggleFullScreen(TheScreen);

I don't see why it would fail to toggle fullscreen? Unless there is a limitation in SDL regarding higher resolutions.

**Comment by Andrettin** [comment]
It would be really nice if a SDL2 port was implemented in Stratagus upstream, but unfortunately that port seems abandoned :( There haven't been any commits in over 3 months.

**Comment by akien-mga** [comment]
> Did you try turning off fullscreen, putting the resolution at 1600x900, and then turning fullscreen on again?

Yes that's what I'm using. The game then goes into fullscreen properly, but the UI is not stretched: so I have a 1600x900 window in the middle and black bars on the sides.

> It would be really nice if a SDL2 port was implemented in Stratagus upstream, but unfortunately that port seems abandoned :( There haven't been any commits in over 3 months.

No commit in 3 months is far from being dead for a slow-paced project like Stratagus ;-)

**Comment by akien-mga** [comment]
> Yes that's what I'm using. The game then goes into fullscreen properly, but the UI is not stretched: so I have a 1600x900 window in the middle and black bars on the sides.

Actually the feature does work, the problem was on my end. My monitor does not provide support for lower widescreen resolutions (1600x900, 1280x720), so when going fullscreen with one of those resolutions, SDL does not change the monitor resolution.

After adding those two lower resolutions to the configurable file or the Xorg server (/etc/X11/xorg.conf), the feature works fine, I can play fullscreen with lower resolutions :)

**Comment by Andrettin** [comment]
Great to hear :)
