### ISSUE TITLE
Tech tree menu restarts the main menu music

### ISSUE THREAD

**Issue by akien-mga** [Andrettin/Wyrmgus#35]
When going to the tech tree submenu in the single player menu, the music restarts instead of continuing to play. It also restarts when switching between the various civilisations, and when leaving the tech tree menu and afterwards when entering another menu.

**Comment by Andrettin** [comment]
Thanks for the report! Fixed in https://github.com/Andrettin/Wyrmsun/commit/76a95714e61081f7db1539dbd24a2f84c364ab0e

**Comment by akien-mga** [comment]
Thanks :) BTW, what's your preference for bug reports? Should they go in the wyrmgus or wyrmsun repo?

**Comment by Andrettin** [comment]
I would generally use the Wyrmsun repo, but both are perfectly fine since I get an email about the issue either way :)
