### ISSUE TITLE
Crash when loading a savegame

### ISSUE THREAD

**Issue by matgh** [Andrettin/Wyrmgus#36]
Whenever I want to load a savegame the game crashes. How can I upload the dmp file here?

Windows 8 with compatibility mode for windows 7

**Comment by matgh** [comment]
I re-installed the game. In the first mission I could save and load properly. Only when I tried to do this in the second mission the game crashed. Even if I went back to mission 1 the game kept crashing.

**Comment by Andrettin** [comment]
Hey, thanks for the bug report! I identified the issue and fixed it in https://github.com/Andrettin/Wyrmgus/commit/1a50aac29856e5ca777a0eae667a89df7183abb7
