### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#37]
Ubuntu 15.04 x86_64, the latest rev. of Wyrmgus (ff6f774916029f23db40b240b1d98981c844060c), there is a compilation problem than can be fixed by modifying /src/map/map.cpp:1342 to

fprintf(stderr, "Couldn't save map setup : '%s' \n", sms_filename.c_str());

Don't want to create a pull request for this.

**Comment by Andrettin** [comment]
Thank you for reporting this :) Fixed now in https://github.com/Andrettin/Wyrmgus/commit/9c46f51c9a90ab3aaefdc13f8ac240f5d545bedc
