### ISSUE TITLE
Finishing quest from savegame doesn't return to quest menu

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#39]
If you start a quest from quest menu, after the mission is over it is possible to spend Tech points on this or that improvement. If you load saved quest game, after the mission is over it doesn't suggest spending Tech points.

**Comment by Andrettin** [comment]
Thanks for the bug report! This was a Lua code issue, fixed in this Wyrmsun commit:
https://github.com/Andrettin/Wyrmsun/commit/0c3a320aafab3334febbeb0ef1651f9df307b027
