### ISSUE TITLE
First time player problem?

### ISSUE THREAD

**Issue by PhoenixRiver** [Andrettin/Wyrmgus#41]
I ran wyrmgus for the first time and got this message:

$ wyrmgus
Can't open file 'preferences.lua': No such file or directory
/usr/games/wyrmgus: line 5: 21946 Segmentation fault /usr/lib/games/wyrmgus/wyrmgus -d /usr/share/games/wyrmsun/ "$@"

I'm running Xubuntu 64-bit (14.04) and wyrmgus (1.5.2.-1~getdeb1 from Playdeb) reports:

$ wyrmgus -h
Wyrmsun v2.3.0, Copyright (c) 1998-2015 by The Stratagus Project
  written by Lutz Sammer, Fabrice Rossi, Vladi Shabanski, Patrice Fortier,
  Jon Gabrielson, Andreas Arens, Nehal Mistry, Jimmy Salmon, Pali Rohar,
  cybermind and others.
[snip]

Seems like a file is missing but if you've run it before it's not a problem?

**Comment by akien-mga** [comment]
Most likely the guys at PlayDeb forgot to define ```ENABLE_USEGAMEDIR=OFF``` in the CMake call, so wyrmgus tries to load its configuration from the game data dir (which is read-only).

It's not the first time I see PlayDeb games crashing out of the box, I guess they don't really test their packages...

**Comment by Andrettin** [comment]
That seems like the probable source of the issue, Akien. The preferences.lua file is created by the game if it doesn't exist, so the directory being read-only would explain that.

**Comment by akien-mga** [comment]
So the next step would be to make a bug report at https://bugs.launchpad.net/getdeb.net
@PhoenixRiver if you're willing to do that, it would be great. Then you can also follow up on the update and check that it will fix the issue.

**Comment by PhoenixRiver** [comment]
Okay, I'll sumbit the bug and test it once it updates :)

**Comment by PhoenixRiver** [comment]
Getdeb updated and having installed the update everything starts up :) - thank you :)
