### ISSUE TITLE
Fluidsynth error...

### ISSUE THREAD

**Issue by PhoenixRiver** [Andrettin/Wyrmgus#47]
This is not a crash bug but it might indicate something more problematic elsewhere... (I've not yet noticed any other symptoms).

When I ran wyrmgus I got the following output on the command line:

$ wyrmgus 
Can't open file 'preferences.lua': No such file or directory
Stratagus v2.3.0, Copyright (c) 1998-2015 by The Stratagus Project
  written by Lutz Sammer, Fabrice Rossi, Vladi Shabanski, Patrice Fortier,
  Jon Gabrielson, Andreas Arens, Nehal Mistry, Jimmy Salmon, Pali Rohar,
  cybermind, Andrettin and others.
	https://launchpad.net/stratagus
Compile options ZLIB VORBIS THEORA FLUIDSYNTH MIKMOD OPENGL LINUX X11 

Stratagus may be copied only under the terms of the GNU General Public License
which may be found in the Stratagus source kit.

DISCLAIMER:
This software is provided as-is.  The author(s) can not be held liable for any
damage that might arise from the use of this software.
Use it at your own risk.

fluidsynth: error: Get end of file position failed
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "/home/willow/.stratagus/wyr/"
fluidsynth: error: Unable to open file ""
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont ""
Failed to load the SoundFont: 
Thanks for playing Stratagus.
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  157 (GLX)
  Minor opcode of failed request:  4 (X_GLXDestroyContext)
  Serial number of failed request:  4385
  Current serial number in output stream:  4387

The last bit I've put into a different issue as it appears unrelated and was only added once I quit wyrmgus.
I'm presuming that the fluidsynth problem will affect the music somehow? or else is there a backup system (in which case buring these warnings might be worth it).
Hope this helps.

**Comment by Andrettin** [comment]
Thanks for the report :)FluidSynth was added to the mainline engine (Stratagus), but isn't really used for Wyrmsun (FluidSynth is used for midi files, while Wyrmsun uses). I actually don't even compile Wyrmgus with FluidSynth enabled. I've changed the CMakeFiles.txt to make compiling with FluidSynth be deactivated by default, as it is not necessary for Wyrmsun:
https://github.com/Andrettin/Wyrmgus/commit/01548ba39d70929614ddcdf3b25b0f36503002d1
