### ISSUE TITLE
*** Error in `./stratagus': corrupted double-linked list: 0x000000000cf82770 ***

### ISSUE THREAD

**Issue by Szunti** [Andrettin/Wyrmgus#5]
git master of Wyrmgus and Wyrmsun, third Germanic mission: Northwards to the Sea
My units fought some others.

And I got the title message on the console with the game frozen.

I guess you can't do anything with it, how can I debug this if it happens again?

**Comment by Andrettin** [comment]
This happened exactly when one unit attacked the other? Which sorts of units were they, melee or ranged?

Did you get anything on stderr.txt, and did you get a crash.dmp file? If no crash.dmp file was generated, then one way to debug it would be to compile a debug version of Wyrmgus, and see if you can cause the issue that way (and hopefully be able to generate a crash.dmp file).

**Comment by Szunti** [comment]
I don't know when it happened exactly. I had mostly melee units, but had an archer too. 

I don't find a crash.dmp or stderr.txt anywhere. I didn't installed wyrmgus, I run from the git directory.
I see files in ./wyr  ./wyr/logs, so I guess these should be there, but there is nothing from that run.

stderr.txt: I am on linux, I guess it's not made here, but I ran from terminal, and I still have it:

>Can't open file 'preferences.lua': No such file or directory
>Stratagus V2.3.0, Copyright (c) 1998-2015 by The Stratagus Project
> written by Lutz Sammer, Fabrice Rossi, Vladi Shabanski, Patrice Fortier,
>  Jon Gabrielson, Andreas Arens, Nehal Mistry, Jimmy Salmon, Pali Rohar,
>  cybermind and others.
>	https://launchpad.net/stratagus
>Compile options ZLIB BZ2LIB VORBIS THEORA FLUIDSYNTH MIKMOD MNG OPENGL LINUX X11 
>
>Stratagus may be copied only under the terms of the GNU General Public License
>which may be found in the Stratagus source kit.
>
>DISCLAIMER:
>This software is provided as-is.  The author(s) can not be held liable for any
>damage that might arise from the use of this software.
>Use it at your own risk.
>
>fluidsynth: error: Get end of file position failed
>fluidsynth: error: Couldn't load soundfont file
>fluidsynth: error: Failed to load SoundFont ".//wyr/"
>fluidsynth: error: Unable to open file ""
>fluidsynth: error: Couldn't load soundfont file
>fluidsynth: error: Failed to load SoundFont ""
>Failed to load the SoundFont: 
>Can't open file 'maps/earth/tanais.smp': No such file or directory
>game ends
>Can't open file 'maps/earth/novgorod.smp': No such file or directory
>game ends
>Can't open file 'maps/earth/jutland.smp': No such file or directory
>*** Error in `./stratagus': corrupted double-linked list: 0x000000000cf82770 ***

crash.dmp: the game was frozen (the cursor didn't move, no reaction for input), I had to kill it.
So it probably wasn't created.

**Comment by Andrettin** [comment]
Seems to have been an issue with forests regenerating while at the border of a map; that has been fixed in commit 215.
