### ISSUE TITLE
libpng16 migration

### ISSUE THREAD

**Issue by a-detiste** [Andrettin/Wyrmgus#56]
Debian is undergoing libpng16 migration.

Please
1) replace libpng12-dev  with libpng-dev 
2) ensure that stratagus still build.

---

I might tackle this myself when libpng16 hits unstable;
so this is merely a reminder that doesn't require urgent reaction.

**Comment by akien-mga** [comment]
I've been building wyrmgus with libpng16 from the beginning, so I guess it will work on Debian too.

**Comment by a-detiste** [comment]
thx

**Comment by a-detiste** [comment]
Please also move to debhelper 9 (debian/compat & debian/control in both Wyrmsun & Wyrmgus)

I don't have a 12.04 Ubuntu (& don't want) to test these changes;
so maybe this can be fixed in Stratagus but not yet in Wyrmgus

**Comment by Andrettin** [comment]
Closed as the game no longer has libpng as a direct dependency, instead it relies on it indirectly via Qt (with QImage).
