### ISSUE TITLE
Can't open file 'maps/earth/*.smp': No such file or directory

### ISSUE THREAD

**Issue by Szunti** [Andrettin/Wyrmgus#6]
I start the game with ./stratagus -d /dir/to/wyrmsun/git/repository

It definitely works, but every time I start a quest I see on the console the title message.
But a map loads and the mission is what I expect it to be, so I guess it could find the map after all.

**Comment by Andrettin** [comment]
Ok, this is pretty weird, specially since it seems to load everything fine. Do you get the same message when loading a map through a custom game?

**Comment by Szunti** [comment]
Yes, same with custom game

**Comment by Andrettin** [comment]
Fixed thanks to Szunti's contribution
