### ISSUE TITLE
Wyrmsun crashes after seconds....

### ISSUE THREAD

**Issue by Coach33** [Andrettin/Wyrmgus#69]
Hi Andrettin,

found your game Wyrmsun on a dvd of a german computer mag (version 1.3 or so) and I played the first 5 missions without problems, mission 6 didn´t appear...so I thought let´s check for newer versions, got version 1.96 but my savegames didn´t work. As the game is fun to play anyway I just played the first levels again, now it crashes everytime I try to play mission 5 (battle of magretobia). I tried reinstalling, changing resolution, changing savegames etc...
I´ll attach the crash.dmp, perhaps you find the error...would love to go on with that game ;-)
[crash.zip](https://github.com/Andrettin/Wyrmgus/files/163133/crash.zip)

**Comment by Andrettin** [comment]
Hey, I'm happy you liked the game :)

Version 1.9.6 is a bit old - the latest is 1.9.9. The bug with that quest has been fixed in it. You can get it from here:
https://github.com/Andrettin/Wyrmsun/releases

**Comment by Coach33** [comment]
Thanks a lot! Looking forward to go on! Best Regards ;-)

**Comment by Andrettin** [comment]
You're welcome :)
