### ISSUE TITLE
Tiling bug

### ISSUE THREAD

**Issue by johndh** [Andrettin/Wyrmgus#74]
Check out the trees near the middle of the screen, just west of my Krieger and Speerkampfer units.

![screenshot from 2016-03-13 23 52 59](https://cloud.githubusercontent.com/assets/692397/13735163/b7dc97ea-e97c-11e5-8f5f-269ff4732e18.jpg)

**Comment by Andrettin** [comment]
Fixed :)

https://github.com/Andrettin/Wyrmgus/commit/9fdb5f13b48fe75a07518c88445b54c41c2241d7
