### ISSUE TITLE
Lack of grayed image causes crash

### ISSUE THREAD

**Issue by johndh** [Andrettin/Wyrmgus#78]
```
Can't open file: No such file or directory
Can't load the graphic '/home/john/Wyrmsun//graphics/germanic/icons/archer_grayed.png'
```
I discovered this while playing a Grand Strategy Game with a custom hero.  When it finishes generating the world, select your hero from the bottom-right panel.  If your hero lacks a grayed icon (like a skutan, scout, or guard) the game will immediately crash.  This does not happen with a hero who has a grayed icon (like Durin or a custom axefighter).

I wonder if it would be better to have the engine automatically gray the icon when needed, instead of having to make two copies of every icon?

**Comment by Andrettin** [comment]
Thanks for notifying me of this issue :) I missed the fact that some units which can be used as custom heroes lacked a grayed portrait. I've fixed the issue now, making the engine apply grayscale automatically as you suggested:
https://github.com/Andrettin/Wyrmgus/commit/1d705d4322de581413ca3b79d67a1531b2c3d673
https://github.com/Andrettin/Wyrmsun/commit/d39841c3c0151ebcb94d495a16b0e7ded9562bfa

**Comment by johndh** [comment]
That fixed the crash.  I'm noticing an anomaly, though.  When I play in OpenGL mode, it grays the entire icon, while playing without OpenGL, it grays everything but the team color (which looks really cool in my opinion, but probably isn't what you want).

![with ogl](https://cloud.githubusercontent.com/assets/692397/13801852/5de460c4-eb0c-11e5-9ead-8c6e96aff9ff.jpg)
![without ogl](https://cloud.githubusercontent.com/assets/692397/13801851/5de3b462-eb0c-11e5-8c1a-85c6159ad66b.jpg)

**Comment by Andrettin** [comment]
Ops, that was an oversight, I fixed that now as well:
https://github.com/Andrettin/Wyrmgus/commit/6195df5b794650715006a2ce42c7462dd24f0bc0
