### ISSUE TITLE
Dialogue boxes flickering in Grand Strategy

### ISSUE THREAD

**Issue by johndh** [Andrettin/Wyrmgus#81]
This only happens in Grand Strategy Mode and only with OpenGL turned off.  In quests, they display just fine, including the battles within Grand Strategy, but opening up a menu or dialogue box in the overworld map causes it to flicker in and out of existence.

Here's what it looks like: https://youtu.be/vTWX2x_67Sg

**Comment by Andrettin** [comment]
Thanks for letting me know, fixed now :)

https://github.com/Andrettin/Wyrmgus/commit/c8fcfbf91cefff9be34f20059fc7a2e95ec10b26
