### ISSUE TITLE
Cmake build problem

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#85]
Currently (with commit  5de8c59) it's not possible to compile Wyrmgus in debug mode, as it then requires `liboaml_d.a` in `/src/oaml` but it doesn't compile even if debug mode is set for oaml repo.

**Comment by akien-mga** [comment]
Thanks, I'll check that.

**Comment by akien-mga** [comment]
It seems that even though the debug library is suffixed with ``_d`` in the ``cmake/modules/FindOAML.cmake``, it is actually built without suffix when built in debug mode. Probably something for @marcelofg55 to fix (though on our end I also need to pass the ``CMAKE_BUILD_TYPE`` to the submodule, I'll make a PR for that).
