### ISSUE TITLE
Crash in GSM whilst setting Faction

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#88]
When starting GSM with random world, `SetRandomFaction()` is called. However, sometimes it goes out of bounds as `PlayerRaces.Factions[this->Race][this->Faction]` doesn't exist.

Looks like this happens after custom game is played and your hero reaches the latest faction. (e.g. Kal Kartha). If you simply start new GSM game it works correctly.  Probably something is not cleared/freed correctly.

P.S. seems like I debugged it incorrectly. Will investigate further.

**Comment by Andrettin** [comment]
Thank you :) The issue was that this code was being triggered on the strategic map, rather than only in battles. This caused a crash because it tried to do things like affect units. This is fixed now:

https://github.com/Andrettin/Wyrmgus/commit/a67baf8a34da573d781e6f1e469c36d9aedb61db
