### ISSUE TITLE
Units attacked by critters are on their own

### ISSUE THREAD

**Issue by johndh** [Andrettin/Wyrmgus#89]
If one of your units is attacked by a regular enemy, all of your combat units in the area will rush in to fight, but if one of your units is attacked by a slime or other unaligned critter, the rest of your units will ignore it.  Basically, the only unit recognizing the creature as hostile, is the one being attacked.  Even if given an attack-move or patrol command, they'll walk right past the fight.

**Comment by Andrettin** [comment]
Thanks for the heads up :) This is fixed now:

https://github.com/Andrettin/Wyrmgus/commit/bf7ee610490719ac3282d9782c29a118aa4cb0ff
