### ISSUE TITLE
Undefined diplomacy state

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#94]
![2016-04-11 23-29-35](https://cloud.githubusercontent.com/assets/1813101/14441447/d9168eb8-0045-11e6-8165-781e58965fb2.png)

Firstly shorbear clan was our enemy, before defeating him completely I made Brising clan my enemy (it's a custom game). Before destroying them, I made Sagan tribe neither enemy nor ally and wasn't able to finish the game. After I set them to allies, the game ended. Is it indeed possible to have "neutral" state?

**Comment by Andrettin** [comment]
The neutral state is supposed to be a diplomatic state in which neither of you will attack each other at the moment, but the scenario can't be won without becoming enemies later on.

Imagine for instance the following situation: you are playing a multiplayer game, and you and the other player have become neutral to one another. If all other enemies were destroyed, then you would both win the game while being neutral to one another, while such a joint victory should only be achievable as allies IMO.

**Comment by KroArtem** [comment]
I'm not sure whether to agree or disagree with you. From the one hand, I wasn't playing a multiplayer game. Moreover we didn't have any limitations in scenario to become enemies later on.

**Comment by Andrettin** [comment]
Yes, but I mean, the diplomacy system has to take multiplayer situations in consideration as well.

It's true that you don't have any limitations regarding becoming enemies with your starting allies, but I think that's alright, since it gives you the freedom to not have an allied victory if you prefer.

**Comment by KroArtem** [comment]
It can be a bit confusing, though, maybe it's worth adding a tip about it? Like "you cannot win or lose if you're neutral to other survivals".

**Comment by KroArtem** [comment]
I just want to raise this ticket again. Currently when a player changes its state to enemy, a warning is displayed, however you have to go to main menu -> options -> diplomacy to change your state. It'd be great if a new window will appear with a text like

 

> Sagan tribe changed diplomacy to enemy. What do you want? 
>- [ ] Change to ally
>- [ ] Change to neutral
>- [ ] Change to enemy

**Comment by Andrettin** [comment]
You can just press F9 and you will be led directly to the Diplomacy screen.

Perhaps instead of showing a screen to change the stance, the "enemy" state could be modified, so that other factions are treated as your enemy if they or you have the stance set to "enemy". This seems more intuitive to me, and would avoid having to bother the player with a popup.

**Comment by KroArtem** [comment]
Do you mean that if e.g I change state to "enemy" then those tribe also changes its state to "enemy", right?

**Comment by Andrettin** [comment]
No, I mean the following:

If you have your diplomatic stance set to neutral, and the AI is set to be your enemy, then the AI is nevertheless considered by your units to be your enemy. Basically, the "worst" diplomatic setting of the two players is used for both.

**Comment by KroArtem** [comment]
Sounds reasonable but may be not so obvious for new players (unless a tip is added somewhere to the loading screen)

**Comment by KroArtem** [comment]
Closing this issue as of https://github.com/Andrettin/Wyrmsun/issues/21#issuecomment-504457419
