### ISSUE TITLE
Unclear steps to compile with oaml

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#99]
I had another PC where I git cloned repo and then had some problems building oaml. As it's not stated anywhere (`building_wyrmsun_on_debian_8.txt` is not so obvious related to ubuntu) I understood submodules also need to be downloaded. So `git clone --recursive` did the job. Then I updated all submodules (in this case it is only one) with `git submodule foreach git pull origin master` and that was my fault. 
However, I still think documentation is a bit unclear and it also true for stratagus' documentation.

**Comment by Andrettin** [comment]
What do you recommend to be explicitly said in the documentation?

**Comment by KroArtem** [comment]
I think that old installation file should be cleaned up (I'm not sure stratagus compiles and works under win98 :)), and `building_wyrmsun_on_debian_8.txt` can be extended so it would describe steps required not only for Debian.

**Comment by KroArtem** [comment]
Closing this issue as of https://github.com/Andrettin/Wyrmsun/issues/21#issuecomment-504457419
